title: Pythonで学ぶ！データサイエンス講座
author: 木山 真人
logo: logo.png
copyright: "2025"

only_build_toc_files: true

execute:
  timeout: 1000
  execute_notebooks: force


launch_buttons:
  notebook_interface: jupyterlab
  colab_url: https://colab.research.google.com

repository:
  url: https://github.com/matt76k/ds-seminar
  path_to_book: _sources
  branch: gh-pages

latex:
  latex_documents:
    targetname: book.tex

html:
  favicon: logo.png
  extra_css: 
    - https://fonts.googleapis.com/css2?family=BIZ+UDGothic

sphinx:
  config:
    nb_execution_mode: auto
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    language: ja

  extra_extensions:
    - sphinx_proof
